namespace Native
{
    public enum NET_IF_ACCESS_TYPE
    {
        NET_IF_ACCESS_LOOPBACK = 0,
        NET_IF_ACCESS_BROADCAST,
        NET_IF_ACCESS_POINT_TO_POINT,
        NET_IF_ACCESS_POINT_TO_MULTI_POINT,
        NET_IF_ACCESS_MAXIMUM
    }
}
