using System;

namespace Native
{
    /// <summary>
    /// A value that indicates the source of the notification.
    /// The possible values for this member are defined in the Wlanapai.h header file to values defined in the L2cmn.h header file.
    /// Windows XP with SP3 and Wireless LAN API for Windows XP with SP2:
    /// This parameter is set to WLAN_NOTIFICATION_SOURCE_NONE, WLAN_NOTIFICATION_SOURCE_ALL, or WLAN_NOTIFICATION_SOURCE_ACM.
    /// </summary>
    [Flags]
    public enum WLAN_NOTIFICATION_SOURCE : uint
    {
        /// <summary>
        /// A notification generated by an unknown source.
        /// </summary>
        WLAN_NOTIFICATION_SOURCE_NONE = 0,
        /// <summary>
        /// A notification generated by the 802.1X module.
        /// For more information on these notifications, see the ONEX_NOTIFICATION_TYPE enumeration reference.
        /// </summary>
        WLAN_NOTIFICATION_SOURCE_ONEX = 0X00000004,
        /// <summary>
        /// A notification generated by the auto configuration module.
        /// For more information on these notifications, see the WLAN_NOTIFICATION_ACM enumeration reference.
        /// </summary>
        WLAN_NOTIFICATION_SOURCE_ACM = 0X00000008,
        /// <summary>
        /// A notification generated by the media specific module (MSM).
        /// For more information on these notifications, see the WLAN_NOTIFICATION_MSM enumeration reference.
        /// </summary>
        WLAN_NOTIFICATION_SOURCE_MSM = 0X00000010,
        /// <summary>
        /// A notification generated by the security module.
        /// No notifications are currently defined for WLAN_NOTIFICATION_SOURCE_SECURITY.
        /// </summary>
        WLAN_NOTIFICATION_SOURCE_SECURITY = 0X00000020,
        /// <summary>
        /// A notification generated by independent hardware vendors (IHV).
        /// </summary>
        WLAN_NOTIFICATION_SOURCE_IHV = 0X00000040,
        /// <summary>
        /// A notification generated by the wireless Hosted Network.
        /// For more information on these notifications, see the WLAN_HOSTED_NETWORK_NOTIFICATION_CODE enumeration reference.
        /// This notification source is available on Windows 7 and on Windows Server 2008 R2 with the Wireless LAN Service installed.
        /// </summary>
        WLAN_NOTIFICATION_SOURCE_HNWK = 0X00000080,
        /// <summary>
        /// A notification generated by the 802.1X module.
        /// </summary>
        WLAN_NOTIFICATION_SOURCE_ALL = 0X0000FFFF
    }
}
